
name: Build and Test
  
jobs:
  build-and-run-tests:
    env:
      IS_DOCKER: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.301
      - name: build
        run: dotnet build
      - name: Run Tests
        run: dotnet test
